apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
  - name: Loki
    type: loki
    url: http://loki:3100
    isDefault: false
    access: proxy
    editable: false
    uid: P8E80F9AEF21F6940
    jsonData:
      timeout: 60
      maxLines: 1000
